import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import SideNav from '../components/Tickets/SideNav/SideNav'
import TicketsDashboard from '../components/Tickets/Dashboard/TicketsDashboard'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Bug Tracker</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className='wrapper'>
				<SideNav />
				<TicketsDashboard />
			</div>
		</>
	)
}

export default Home
