import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Feed from '../components/Feed'
import { useSelector } from 'react-redux'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bug Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Tickets feed</h1>
      <Feed />
    </div>
  )
}

export default Home
